"""Documenter role workflow (spec 171): intake, plan, gather, write, gate, pointers, commit, report.

The page set is chosen by code from the documentation brief and the changed
files (or from the repository layout in init mode), each page gets one
schema-guarded write with a no-change option, a gate enforces the page
contract (citations that exist, links that resolve, one kind per page with its
headings, size bounds, no changelog lines), the README index is generated by
code in the llms.txt shape, short pointer sections are refreshed in the agent
instruction files, and one ``docs(#n)`` commit is made through the existing
``commit_files``. Selected by ``workflow: documenter`` on the tech_writer role.
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import TYPE_CHECKING, Any

import structlog

from performer.models import BackendEvent, BackendEventType
from performer.workflows.base import WorkflowResult
from performer.workflows.documenter.budgets import DocumenterBudgets
from performer.workflows.documenter.commit import commit_docs
from performer.workflows.documenter.gate import GateInput, gate_page
from performer.workflows.documenter.gather import gather_page, hunks_for_page, with_analysis_inputs
from performer.workflows.documenter.index import generate_readme
from performer.workflows.documenter.inventory import build_inventory, extract_citations, first_paragraph, path_like_tokens, repository_layout
from performer.workflows.project_shape import ProjectShapeUnknown, repo_tree
from performer.workflows.documenter.models import POINTER_FILES, DocsRecord, PageResult, WikiPage
from performer.workflows.documenter.plan import build_plan
from performer.workflows.documenter.pointers import render_pointer_section, replace_between_markers
from performer.workflows.documenter.report import build_report, write_free_check
from performer.workflows.documenter.write import run_write_step
from performer.workflows.reviewer.diffparse import detect_truncation, parse_unified_diff

if TYPE_CHECKING:
    from performer.models import Score, Stand

log = structlog.get_logger(__name__)

STATES: tuple[str, ...] = ("intake", "plan", "gather", "write", "gate", "pointers", "commit", "report")
WIKI_README = "docs/wiki/README.md"


class DocumenterWorkflow:
    """Sequences the documenter steps; only code advances the sequence."""

    name = "documenter"
    #: 343: ordered steps, the single source for the wire and the latch.
    steps = STATES

    def __init__(self, committer=None) -> None:
        self._committer = committer

    @staticmethod
    def _step(toolkit, name: str, detail: str = "") -> None:
        emit = getattr(toolkit, "emit", None)
        if callable(emit):
            emit(BackendEvent(type=BackendEventType.progress, text=f"documenter.{name}", detail=detail))

    async def run(self, stand: "Stand", score: "Score", toolkit: Any) -> WorkflowResult:
        metrics = toolkit.metrics
        durations = metrics.step_durations_ms
        workspace = Path(getattr(stand, "path", ".") or ".")
        budgets = DocumenterBudgets.from_env(getattr(score, "workflow_env", None) or {})
        mode = str(getattr(score, "doc_mode", "update") or "update")
        issue = getattr(score, "issue_number", None)

        def timed(name: str, started: float) -> None:
            durations[name] = int((time.monotonic() - started) * 1000)

        # intake
        self._step(toolkit, "intake", mode)
        t = time.monotonic()
        clean = await write_free_check(toolkit, workspace)
        if not clean.get("passed"):
            timed("intake", t)
            record = DocsRecord(mode=mode, changed_files=[], plan=[], results=[], files_written=[], verdict="env_blocked",
                                hold_reason="the tree was dirty at start: " + ", ".join(clean.get("dirty_paths") or ["(unknown)"]))
            return self._finish(toolkit, record, metrics)
        tree = await _tree(toolkit, workspace)
        diff_text = str(getattr(score, "pr_diff", "") or "")
        changed = parse_unified_diff(diff_text)
        brief = getattr(score, "documentation_brief", None)
        brief = dict(brief) if isinstance(brief, dict) and brief else {}
        inventory = build_inventory(workspace, tree)
        # 367: the model reads the repository and says what it is. Asked once
        # and only when something actually needs it -- init mode plans from the
        # layout, and the write path puts the project's name on a page. A card
        # with nothing to document never asks, which is what keeps a trivial
        # card free.
        _layout: list = []

        async def layout_or_hold():
            """The reading, memoised. Raises ProjectShapeUnknown to stop."""
            if not _layout:
                _layout.append(await repository_layout(toolkit, workspace, tree))
            return _layout[0]
        timed("intake", t)
        log.info("documenter.intake", mode=mode, files=len(changed), truncated=detect_truncation(diff_text), inventory=len(inventory), brief=bool(brief))

        findings = getattr(score, "documentation_findings", None) or {}
        analysis_paths = []
        for entry in findings.values() if isinstance(findings, dict) else []:
            record_findings = entry.get("findings") if isinstance(entry, dict) else None
            if isinstance(record_findings, dict):
                analysis_paths.extend(p for p in record_findings.get("covered_files", []) if isinstance(p, str))

        # plan (code only)
        self._step(toolkit, "plan")
        t = time.monotonic()
        brief_docs = [d for d in (brief.get("docs") or []) if isinstance(d, dict)]
        # Only init mode plans from the layout; build_plan takes None otherwise,
        # so an update-mode card never pays for a reading it will not consult.
        try:
            layout = await layout_or_hold() if mode == "init" else None
        except ProjectShapeUnknown as exc:
            timed("plan", t)
            log.warning("documenter.project_shape_unknown", reason=exc.reason[:200])
            record = DocsRecord(mode=mode, changed_files=[], plan=[], results=[], files_written=[],
                                verdict="env_blocked",
                                hold_reason="could not work out what this repository is: " + exc.reason[:300])
            return self._finish(toolkit, record, metrics)
        plans, deferred, refused = build_plan(mode, brief_docs, list(dict.fromkeys([f.path for f in changed] + analysis_paths)), inventory, layout, budgets.plan_cap)
        # A brief page without modules of its own gathers the brief's modules, else the
        # changed files: the live round gathered nothing for a new page and the model,
        # rightly, refused to invent paths.
        fallback_modules = [m.get("path", "") if isinstance(m, dict) else m
                            for m in (brief.get("modules") or []) if isinstance(m, (str, dict))]
        fallback_modules = [p for p in fallback_modules if isinstance(p, str) and p] or [f.path for f in changed]
        plans = [pl.model_copy(update={"modules": fallback_modules[: budgets.gather_max_commands]}) if pl.source == "brief" and not pl.modules else pl for pl in plans]
        # Init pages gather their own evidence: the package's files, the project files, the test tree.
        plans = [pl.model_copy(update={"modules": _init_modules(pl, tree, layout)[: budgets.gather_max_commands]}) if pl.source == "init" and not pl.modules else pl for pl in plans]
        timed("plan", t)
        log.info("documenter.plan", pages=[p.path for p in plans], deferred=deferred, refused=refused)
        record = DocsRecord(mode=mode, brief_present=bool(brief), changed_files=[f.path for f in changed], diff_truncated=detect_truncation(diff_text),
                            inventory_size=len(inventory), plan=plans, deferred=deferred, refused_paths=refused, results=[], files_written=[], verdict="docs_committed")
        if not plans:
            log.info("documenter.nothing_to_do")
            return self._finish(toolkit, record, metrics)

        pages_by_path = {p.path: p for p in inventory}
        writes: dict[str, str] = {}
        retirements: list[str] = []
        results: list[PageResult] = []
        for plan in plans:
            if plan.source == "index":
                continue  # the README is generated by code after the pages settle
            self._step(toolkit, "gather", plan.path)
            t = time.monotonic()
            evidence, current, evidence_text = await gather_page(toolkit, workspace, plan, max_commands=budgets.gather_max_commands, max_output_chars=budgets.gather_max_output_chars)
            evidence_text = with_analysis_inputs(evidence_text, findings,
                                                 max_chars=budgets.gather_max_commands * budgets.gather_max_output_chars)
            record.evidence[plan.path] = evidence.model_dump()
            page = pages_by_path.get(plan.path)
            hunks = hunks_for_page(plan, changed, page.citations if page else [], diff_text)
            durations["gather"] = durations.get("gather", 0) + int((time.monotonic() - t) * 1000)

            self._step(toolkit, "write", plan.path)
            t = time.monotonic()
            out = await run_write_step(toolkit, plan, current_content=current, evidence=evidence_text, changed_hunks=hunks, max_chars=budgets.page_max_chars)
            durations["write"] = durations.get("write", 0) + int((time.monotonic() - t) * 1000)

            self._step(toolkit, "gate", plan.path)
            t = time.monotonic()
            pages_after = (set(pages_by_path) | {p.path for p in plans}) - set(retirements)
            result = gate_page(GateInput(plan=plan, action=out.action, content=out.content, reason=out.reason, tree=tree, pages_after_run=pages_after, inventory_page=page))
            results.append(result)
            durations["gate"] = durations.get("gate", 0) + int((time.monotonic() - t) * 1000)
            log.info("documenter.gate", path=plan.path, action=result.action, dropped=result.dropped, reason=result.drop_reason)
            if result.dropped:
                continue
            if result.action == "write":
                writes[plan.path] = out.content
            elif result.action == "retire":
                retirements.append(plan.path)

        # index: the README is generated by code from the surviving inventory
        final_pages = _final_inventory(inventory, writes, retirements, tree)
        changed_wiki = bool(writes) or bool(retirements)
        index_only = all(pl.source == "index" for pl in plans)
        if changed_wiki or mode == "init" or index_only:
            summary = _summary(inventory, brief, workspace)
            # The second call site for the reading, and the one the laziness
            # created: in update mode the plan never asked, so this is where a
            # repository nobody could characterise first surfaces. Adversarial
            # review found it unguarded -- the stop became an unhandled
            # exception here instead of the env_blocked hold it is everywhere
            # else, which is a crash where the design promises a hold.
            try:
                project = (await layout_or_hold()).project_name or _project_name(workspace)
            except ProjectShapeUnknown as exc:
                log.warning("documenter.project_shape_unknown", reason=exc.reason[:200], phase="write")
                record.verdict = "env_blocked"
                record.hold_reason = "could not work out what this repository is: " + exc.reason[:300]
                return self._finish(toolkit, record, metrics)
            readme = generate_readme(project, summary, [p for p in final_pages if p.path != WIKI_README])
            writes[WIKI_README] = readme
            record.readme_generated = True
            results.append(PageResult(path=WIKI_README, kind=None, action="generated", dropped=False, size=len(readme)))

        # Early runs share the implementation branch and stay strictly in docs/.
        # Root agent pointers are refreshed only by final reconciliation.
        # pointers
        if not getattr(score, "documenting_side_run", False) and (changed_wiki or mode == "init" or index_only):
            self._step(toolkit, "pointers")
            t = time.monotonic()
            first_three = [(p.title, p.path) for p in final_pages if p.path != WIKI_README][:3]
            section = render_pointer_section(WIKI_README, first_three)
            for name in POINTER_FILES:
                target = workspace / name
                existing = target.read_text() if target.exists() else ""
                updated = replace_between_markers(existing, section)
                if updated != existing:
                    writes[name] = updated
                    record.pointers_refreshed.append(name)
            timed("pointers", t)

        record.results = results
        record.files_written = sorted(writes)
        record.files_retired = list(retirements)

        # commit: exactly once, through the existing path
        if writes or retirements:
            self._step(toolkit, "commit", f"{len(writes)} write(s), {len(retirements)} retirement(s)")
            t = time.monotonic()
            message = f"docs(#{issue}): {_commit_summary(brief, writes)}" if issue else f"docs: {_commit_summary(brief, writes)}"
            try:
                committed = await commit_docs(stand, score, files=[{"path": p, "content": c} for p, c in writes.items()], deletions=retirements, message=message, committer=self._committer)
                record.files_written = sorted(p for p in committed if p in writes) or sorted(writes)
                record.commit_sha = await _head(toolkit, workspace)
            except Exception as exc:  # noqa: BLE001 - the hold names the failure
                log.warning("documenter.commit_failed", error=str(exc)[:300])
                record.verdict = "env_blocked"
                record.hold_reason = f"the docs commit failed: {str(exc)[:300]}"
                record.files_written = []
                record.files_retired = []
            timed("commit", t)
        return self._finish(toolkit, record, metrics)

    def _finish(self, toolkit, record: DocsRecord, metrics) -> WorkflowResult:
        self._step(toolkit, "report", record.verdict)
        record.workflow_metrics = {"model_calls": metrics.model_calls, "commands_run": metrics.commands_run}
        report = build_report(record, metrics)
        raw_events = getattr(toolkit, "events", [])
        events = list(raw_events() if callable(raw_events) else raw_events)
        return WorkflowResult(report=report, findings=[], events=events, metrics=metrics)


async def _tree(toolkit, workspace: Path) -> set[str]:
    """Kept as a name this module already uses; the reading lives in one place."""
    return await repo_tree(toolkit, workspace)


async def _head(toolkit, workspace: Path) -> str | None:
    result = await toolkit.run_command("git rev-parse HEAD", cwd=workspace, timeout_s=30)
    sha = (result.output_excerpt or "").strip().splitlines()
    return sha[0][:40] if sha and result.exit_code == 0 else None


def _final_inventory(inventory: list[WikiPage], writes: dict[str, str], retirements: list[str], tree: set[str]) -> list[WikiPage]:
    by_path = {p.path: p for p in inventory if p.path not in retirements}
    for path, content in writes.items():
        if not path.startswith("docs/wiki/"):
            continue
        from performer.workflows.documenter import markdown as md  # noqa: PLC0415
        fm, _body = md.parse_frontmatter(content)
        h1 = [h.text for h in md.headings(content) if h.level == 1]
        by_path[path] = WikiPage(path=path, kind=fm.get("kind"), title=(h1[0] if h1 else Path(path).stem), citations=extract_citations(content, tree | path_like_tokens(content)), links=[], size=len(content), summary=first_paragraph(content))
    return sorted(by_path.values(), key=lambda p: p.path)


def _summary(inventory: list[WikiPage], brief: dict, workspace: Path) -> str:
    from performer.workflows.documenter import markdown as md  # noqa: PLC0415

    readme = workspace / WIKI_README
    if readme.exists():
        quote = md.blockquote_under_h1(readme.read_text())
        if quote:
            return quote
    return str(brief.get("summary") or "Project documentation for developers and coding agents.")


def _init_modules(plan, tree: set[str], layout) -> list[str]:
    """Evidence files for an init-mode page, chosen by the page's role (live round: none were gathered)."""
    project_files = [p for p in ("pyproject.toml", "package.json", "README.md", "Makefile", "setup.cfg", "pytest.ini") if p in tree]
    ci = sorted(p for p in tree if p.startswith(".github/workflows/"))[:2]
    stem = Path(plan.path).stem
    if stem == "architecture":
        mains = []
        for pkg in (layout.packages if layout else [])[:4]:
            files = sorted(p for p in tree if p.startswith(pkg["path"] + "/") and p.endswith((".py", ".ts", ".js", ".go", ".rs", ".rb")))
            mains.extend(files[:1])
        return project_files[:1] + mains
    if stem == "setup":
        return project_files + ci
    if stem == "testing":
        tests = sorted(p for p in tree if p.split("/", 1)[0] in ("tests", "test") or "/tests/" in p or "/test/" in p)
        return project_files[:1] + tests[:4]
    pkg_files = sorted(p for p in tree if p.startswith(stem + "/") and not any(seg in ("tests", "test") for seg in p.split("/")[1:-1]))
    return pkg_files[:5]


def _project_name(workspace: Path) -> str:
    return workspace.resolve().name or "project"


def _commit_summary(brief: dict, writes: dict[str, str]) -> str:
    text = str(brief.get("summary") or "").strip()
    if text:
        return text[:60]
    pages = [Path(p).stem for p in writes if p.startswith("docs/wiki/")]
    return ("update wiki: " + ", ".join(pages[:4]))[:72] if pages else "update documentation"


__all__ = ["DocumenterWorkflow", "STATES"]
