#!/usr/bin/env python3
"""Consolidate the persona sweep into a committed cross-model report (077).

Reads every specs/077-multi-backend-qa/persona_runs/<model>/results.json and
emits, under specs/077-multi-backend-qa/:
  persona_report.json  — flat rows (queryable) + rollups
  persona_report.md    — leaderboards, best (model,backend) per persona, and a
                         harness-fix triage (what's *ours* to fix vs model-can't)

Re-runnable any time. Used after the sweep to answer "which model on which
backend for which persona, and what needs fixing."
"""
from __future__ import annotations

import collections
import glob
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from smoke_backends import REPO_ROOT

BASE = REPO_ROOT / "specs" / "077-multi-backend-qa" / "persona_runs"
OUT = REPO_ROOT / "specs" / "077-multi-backend-qa"

# Failure-signature buckets for the triage (ordered; first match wins).
SIGNATURES = [
    ("model lacks tool-calling (route elsewhere)", ("does not support tools",)),
    ("model lacks thinking (route claude_code elsewhere)", ("does not support thinking",)),
    ("junie standalone-issue build crash", ("issue.md.junie_standalone", "junie_standalone")),
    ("backend parse failure on valid output", ("backend_format_error",)),
    ("backend subprocess crash", ("subprocess_exit",)),
    ("workspace/dispatch setup error", ("dispatch_error", "workspacesetup")),
    ("transport / connection drop", ("server disconnected", "connection reset",
                                     "connection refused", "transport error", "unreachable")),
    ("upstream timeout / hang", ("timeout", "timed out")),
]


def _signature(row: dict) -> str:
    blob = f"{row.get('detail','')} {row.get('error_code','')} {row.get('status','')}"
    # The rich failure text (does-not-support-tools, crash traces, junie build
    # error) lives in the committed per-cell log, not the summary row — pull it in.
    lf = row.get("log_file")
    if lf and row.get("_dir"):
        try:
            d = json.loads(Path(row["_dir"], lf).read_text())
            blob += " " + (d.get("summary") or "") + " " + (d.get("logs_excerpt") or "")
            blob += " " + (d.get("container_logs") or "")[-4000:]
        except Exception:
            pass
    blob = blob.lower()
    for label, needles in SIGNATURES:
        if any(n in blob for n in needles):
            return label
    return "other / uncategorised"


def main() -> int:
    rows = []
    for d in sorted(glob.glob(str(BASE / "*") + "/")):
        if "shakeout" in d or not os.path.exists(d + "results.json"):
            continue
        batch = json.loads(Path(d, 'results.json').read_text())
        for r in batch:
            r["_dir"] = d
        rows.extend(batch)
    if not rows:
        print("no persona results found")
        return 1
    for r in rows:
        r["model_key"] = (r.get("model") or "").replace("local/", "")

    models = sorted({r["model_key"] for r in rows})
    backends = sorted({r["backend"] for r in rows})
    personas = ["assessor", "architect", "implementer", "reviewer", "security",
                "qa", "tech_writer", "closer", "env_bootstrap"]
    personas = [p for p in personas if any(r["role"] == p for r in rows)] + \
               sorted({r["role"] for r in rows} - set(personas))

    def rate(sub):
        n = len(sub)
        p = sum(1 for r in sub if r["category"] == "PASS")
        return p, n

    cat = collections.Counter(r["category"] for r in rows)
    lines = []
    lines.append("# Persona capability report — 24 models x 7 backends x 9 personas")
    lines.append("")
    lines.append(f"_{len(rows)} cells · PASS {cat['PASS']} ({100*cat['PASS']//len(rows)}%) · "
             f"FAIL_MODEL {cat['FAIL_MODEL']} · FAIL_HARNESS {cat['FAIL_HARNESS']} · "
             f"ERROR {cat['ERROR']}. Generated by scripts/persona_consolidate.py._")
    lines.append("")
    lines.append("Legend: **PASS** met the contract + behavioural bar · **FAIL_MODEL** ran but "
             "got it wrong · **FAIL_HARNESS** fixable plumbing · **ERROR** crash/timeout.")

    # Model leaderboard
    lines += ["", "## Model leaderboard (overall PASS-rate)", "", "| model | PASS | rate |", "|---|---|---|"]
    for m in sorted(models, key=lambda m: -rate([r for r in rows if r["model_key"] == m])[0] /
                    max(1, rate([r for r in rows if r["model_key"] == m])[1])):
        p, n = rate([r for r in rows if r["model_key"] == m])
        lines.append(f"| `{m}` | {p}/{n} | {100*p//n}% |")

    # Backend leaderboard
    lines += ["", "## Backend leaderboard (overall PASS-rate)", "", "| backend | PASS | rate |", "|---|---|---|"]
    for b in sorted(backends, key=lambda b: -rate([r for r in rows if r["backend"] == b])[0] /
                    max(1, rate([r for r in rows if r["backend"] == b])[1])):
        p, n = rate([r for r in rows if r["backend"] == b])
        lines.append(f"| {b} | {p}/{n} | {100*p//n}% |")

    # Persona difficulty
    lines += ["", "## Persona difficulty (PASS-rate, hardest first)", "", "| persona | PASS | rate |", "|---|---|---|"]
    for p_ in sorted(personas, key=lambda p_: rate([r for r in rows if r["role"] == p_])[0] /
                     max(1, rate([r for r in rows if r["role"] == p_])[1])):
        p, n = rate([r for r in rows if r["role"] == p_])
        lines.append(f"| {p_} | {p}/{n} | {100*p//n}% |")

    # Best (model, backend) per persona — the recommendation table
    lines += ["", "## Recommended (model, backend) per persona", "",
          "_All combos that PASSed, ranked by judge quality where available. "
          "'— none —' means no model/backend passed this persona._", ""]
    recs = {}
    for p_ in personas:
        winners = [r for r in rows if r["role"] == p_ and r["category"] == "PASS"]
        winners.sort(key=lambda r: -(r.get("judge_quality") or 0))
        recs[p_] = [{"model": r["model_key"], "backend": r["backend"],
                     "judge_quality": r.get("judge_quality")} for r in winners]
        if winners:
            top = ", ".join(f"`{r['model_key']}`/{r['backend']}"
                            + (f"(q{r.get('judge_quality')})" if r.get('judge_quality') else "")
                            for r in winners[:4])
            extra = f" … +{len(winners)-4} more" if len(winners) > 4 else ""
            lines.append(f"- **{p_}** ({len(winners)} passing): {top}{extra}")
        else:
            lines.append(f"- **{p_}**: — none passed — (strongest case for the planner/executor split, spec 080)")

    # Harness-fix triage
    lines += ["", "## Harness-fix triage (FAIL_HARNESS + ERROR by signature)", "",
          "_What's *ours* to fix vs. a hard model limit. Counts across all cells._", "",
          "| signature | cells | kind |", "|---|---|---|"]
    nonpass = [r for r in rows if r["category"] in ("FAIL_HARNESS", "ERROR")]
    sigcount = collections.Counter(_signature(r) for r in nonpass)
    kind = {
        "model lacks tool-calling (route elsewhere)": "routing (model)",
        "model lacks thinking (route claude_code elsewhere)": "routing (model)",
        "junie standalone-issue build crash": "FIX (harness)",
        "backend parse failure on valid output": "FIX (harness)",
        "backend subprocess crash": "investigate (harness)",
        "workspace/dispatch setup error": "investigate (harness)",
        "transport / connection drop": "infra/transient",
        "upstream timeout / hang": "infra/transient",
        "other / uncategorised": "triage",
    }
    for sig, c in sigcount.most_common():
        lines.append(f"| {sig} | {c} | {kind.get(sig,'triage')} |")

    OUT.joinpath("persona_report.md").write_text("\n".join(lines) + "\n")
    OUT.joinpath("persona_report.json").write_text(json.dumps({
        "totals": dict(cat), "n_cells": len(rows),
        "models": models, "backends": backends, "personas": personas,
        "recommendations": recs,
        "triage": dict(sigcount),
    }, indent=2))
    print(f"Wrote {OUT/'persona_report.md'} and persona_report.json")
    print(f"  {len(rows)} cells, PASS {cat['PASS']} ({100*cat['PASS']//len(rows)}%)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
